[package]
name = "pygm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pygm"
crate-type = ["cdylib"]

[dependencies]
libsm = "0.6.0"
hex = "0.4.3"
pyo3 = "0.20.0"
rand = "0.8.5"
